name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and publish
        run: |
          dotnet build --configuration Release --no-restore
          dotnet publish EventManagerPK/EventManagerPK.csproj -c Release -o publish

      - name: Change base tag in index.html
        run: |
          sed -i 's/<base href="\/EventEasePK" \/>/<base href="\/EventEasePK\/" \/>/g' publish/wwwroot/index.html

      - name: Add .nojekyll file
        run: touch publish/wwwroot/.nojekyll

      - name: Copy index.html to 404.html
        run: cp publish/wwwroot/index.html publish/wwwroot/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: publish/wwwroot
          branch: gh-pages
          clean: true